app:
  title: "Multi-PDF Chatbot"
  page_icon: "ðŸ“š"
  layout: "centered"
  header: "Hossein's AI assistant chatbot "
  welcome_message: "Ø³Ù„Ø§Ù… ðŸ‘‹ØŒ Ø§Ú¯Ø± Ø³ÙˆØ§Ù„ÛŒ Ø¯Ø± Ù…ÙˆØ±Ø¯ Ø±Ø²ÙˆÙ…Ù‡ Ù…Ù† Ø¯Ø§Ø±ÛŒØ¯ Ù…ÛŒ ØªÙˆÙ†ÛŒØ¯ Ø¨Ù¾Ø±Ø³ÛŒØ¯ "

data:
  pdf_paths:
    - "data/CV.pdf"
    - "data/Cover_Letter.pdf"

llm:
  model_name: "models/gemini-2.5-flash"
  temperature: 0.2

rag:
  chunk_size: 1000
  chunk_overlap: 100
  top_k: 4

chat:
  history_limit: 6
  system_prompt: |
    You are a helpful AI assistant. Use the provided context (from multiple PDFs) and chat history to answer.
    If you don't know, just say "I don't know".


debug:
  clear_cache: false         # set true to clear st.cache_resource
  verbose: true              # show extra logs in Streamlit
